"""通用工具：命名、网络下载、ffmpeg 合并。"""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
import time
import unicodedata
from pathlib import Path

import httpx

# 平台 → cookie 作用域
COOKIE_DOMAIN = {
    "douyin": ".douyin.com",
    "tiktok": ".tiktok.com",
    "instagram": ".instagram.com",
    "twitter": ".twitter.com",
    "youtube": ".youtube.com",
    "bilibili": ".bilibili.com",
}


def netscape_cookiefile(cookie: str, platform: str) -> Path | None:
    """把 cookie 字符串写成 Netscape 格式文件（yt-dlp 推荐方式）。"""
    if not cookie:
        return None
    domain = COOKIE_DOMAIN.get(platform)
    if not domain:
        return None
    expire = int(time.time()) + 7 * 86400
    lines = ["# Netscape HTTP Cookie File", "# Generated by dl"]
    for part in cookie.split(";"):
        part = part.strip()
        if "=" not in part:
            continue
        name, _, value = part.partition("=")
        name, value = name.strip(), value.strip()
        if name:
            lines.append(f"{domain}\tTRUE\t/\tFALSE\t{expire}\t{name}\t{value}")
    path = Path(tempfile.gettempdir()) / f"dl_cookies_{platform}.txt"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path

ILLEGAL = r'[\\/:*?"<>|\r\n\t]'


def safe_filename(name: str, limit: int = 60) -> str:
    name = unicodedata.normalize("NFKC", name or "")
    name = re.sub(ILLEGAL, "_", name)
    name = re.sub(r"\s+", " ", name).strip().strip(".")
    if len(name) > limit:
        name = name[:limit].rstrip()
    return name or "untitled"


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def ffmpeg_bin() -> str:
    exe = shutil.which("ffmpeg")
    if not exe:
        raise RuntimeError("未找到 ffmpeg，请安装并加入 PATH")
    return exe


def merge_av(video: Path, audio: Path, out: Path) -> Path:
    """无损合并（-c copy），保持原始画质，不重编码。"""
    tmp = out.with_suffix(".merging.mp4")
    cmd = [
        ffmpeg_bin(), "-y", "-hide_banner", "-loglevel", "error",
        "-i", str(video), "-i", str(audio),
        "-c", "copy", "-movflags", "+faststart", str(tmp),
    ]
    subprocess.run(cmd, check=True)
    tmp.replace(out)
    video.unlink(missing_ok=True)
    audio.unlink(missing_ok=True)
    return out


def probe_size(path: Path) -> tuple[int, int]:
    """用 ffprobe 读回实际分辨率（0,0 表示失败）。"""
    exe = shutil.which("ffprobe")
    if not exe:
        return 0, 0
    try:
        res = subprocess.run(
            [exe, "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=width,height", "-of", "csv=p=0", str(path)],
            capture_output=True, text=True, check=True, timeout=30,
        )
        w, h = res.stdout.strip().split(",")[:2]
        return int(w), int(h)
    except Exception:
        return 0, 0


def client(cfg) -> httpx.Client:
    headers = {
        "User-Agent": cfg.user_agent,
        "Accept": "*/*",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        "Referer": "https://www.douyin.com/",
    }
    return httpx.Client(
        headers=headers,
        proxy=cfg.proxy or None,
        timeout=httpx.Timeout(cfg.timeout, connect=10),
        follow_redirects=True,
        http2=False,
    )


def stream_download(cli: httpx.Client, url: str, dest: Path, referer: str | None = None,
                    chunk: int = 1 << 20) -> Path:
    """流式下载大文件，先写 .part，完成后原子改名（支持断点续跑）。"""
    dest.parent.mkdir(parents=True, exist_ok=True)
    part = dest.with_suffix(dest.suffix + ".part")
    headers = {}
    if referer:
        headers["Referer"] = referer
    resume = part.stat().st_size if part.exists() else 0
    if resume:
        headers["Range"] = f"bytes={resume}-"

    with cli.stream("GET", url, headers=headers) as resp:
        if resume and resp.status_code == 200:
            resume = 0  # 服务端不支持续传，重头写
        resp.raise_for_status()
        mode = "ab" if resume else "wb"
        with open(part, mode) as fh:
            for block in resp.iter_bytes(chunk):
                fh.write(block)
    part.replace(dest)
    return dest


def fetch_bytes(cli: httpx.Client, url: str, referer: str | None = None) -> bytes:
    headers = {"Referer": referer} if referer else {}
    resp = cli.get(url, headers=headers)
    resp.raise_for_status()
    return resp.content
